// Test IDs for the Task Detail screen + Category Management screen.

export const DETAIL = {
  screen: 'task-detail-screen',
  back: 'task-detail-back-button',
  edit: 'task-detail-edit-button',
  toggleStatus: 'task-detail-toggle-status-button',
  delete: 'task-detail-delete-button',
  cancelTask: 'task-detail-cancel-button',
  copy: 'task-detail-copy-button',
  copyModal: 'task-detail-copy-modal',
  copyIncludeSubtasks: 'task-detail-copy-include-subtasks',
  copyIncludeAttachments: 'task-detail-copy-include-attachments',
  copyConfirm: 'task-detail-copy-confirm',
  copyCancel: 'task-detail-copy-cancel',
  startDate: 'task-detail-start-date',
  deleteConfirm: 'task-detail-delete-confirm',
  deleteCancel: 'task-detail-delete-cancel',
  subtaskInput: 'task-detail-subtask-input',
  subtaskAdd: 'task-detail-subtask-add-button',
  subtaskToggle: 'task-detail-subtask-toggle',
  subtaskDelete: 'task-detail-subtask-delete',
  reminderChip: 'task-detail-reminder-chip',
  myCompletion: 'task-detail-my-completion-toggle',
  reassign: 'task-detail-reassign-button',
  reassignSearch: 'task-detail-reassign-search',
  reassignUser: 'task-detail-reassign-user',
  reassignClose: 'task-detail-reassign-close',
  attachAdd: 'task-detail-attach-add',
  attachItem: 'task-detail-attach-item',
  attachDelete: 'task-detail-attach-delete',
  attachDeleteConfirm: 'task-detail-attach-delete-confirm',
  attachChooserCamera: 'task-detail-attach-camera',
  attachChooserLibrary: 'task-detail-attach-library',
  attachChooserDocument: 'task-detail-attach-document',
  attachPreviewClose: 'task-detail-attach-preview-close',
  attachSettings: 'task-detail-attach-settings',
  shareAdd: 'task-detail-share-add',
  shareItem: 'task-detail-share-item',
  shareRemove: 'task-detail-share-remove',
  shareSearch: 'task-detail-share-search',
  shareUser: 'task-detail-share-user',
  sharePerm: 'task-detail-share-perm',
  shareSave: 'task-detail-share-save',
  shareClose: 'task-detail-share-close',
  // Wave 3 — Görev Bağlama (grup) bölümü
  groupSection: 'task-detail-group-section',
  groupMember: 'task-detail-group-member',
  groupRemoveMember: 'task-detail-group-remove-member',
  groupEdit: 'task-detail-group-edit',
  groupDissolve: 'task-detail-group-dissolve',
  groupLinkOpen: 'task-detail-group-link-open',
  // Wave 4 — Görev Kilidi + OTP bölümü
  lockSection: 'task-detail-lock-section',
  lockConfigOpen: 'task-detail-lock-config-open',
  lockIssueOtp: 'task-detail-lock-issue-otp',
  lockUnlockOpen: 'task-detail-lock-unlock-open',
  lockUnlockSimple: 'task-detail-lock-unlock-simple',
  lockFlag: 'task-detail-lock-flag',
  lockRequiresOtp: 'task-detail-lock-requires-otp',
  lockSetAll: 'task-detail-lock-set-all',
  lockClearAll: 'task-detail-lock-clear-all',
  lockConfigSave: 'task-detail-lock-config-save',
  lockConfigCancel: 'task-detail-lock-config-cancel',
  lockTabConfig: 'task-detail-lock-tab-config',
  lockTabHistory: 'task-detail-lock-tab-history',
  lockHistoryRefresh: 'task-detail-lock-history-refresh',
  otpCode: 'task-detail-otp-code',
  otpCopy: 'task-detail-otp-copy',
  otpClose: 'task-detail-otp-close',
  unlockInput: 'task-detail-unlock-input',
  unlockSubmit: 'task-detail-unlock-submit',
  unlockCancel: 'task-detail-unlock-cancel',
};

export const CATMGR = {
  screen: 'category-manager-screen',
  back: 'category-manager-back-button',
  addRoot: 'category-add-root-button',
  node: 'category-node',
  addSub: 'category-add-sub-button',
  edit: 'category-edit-button',
  delete: 'category-delete-button',
  editorModal: 'category-editor-modal',
  nameInput: 'category-name-input',
  colorSwatch: 'category-color-swatch',
  companyChip: 'category-company-chip',
  companySearch: 'category-company-search-input',
  parentChip: 'category-parent-chip',
  save: 'category-editor-save-button',
  cancel: 'category-editor-cancel-button',
  deleteConfirm: 'category-delete-confirm',
  deleteCancel: 'category-delete-cancel',
  open: 'tasks-open-categories-button',
};
